compile:
	g++ ServerMain.cpp ServerFunct.cpp ServerFunct.h  -o BattleShipServer.exe -std=c++0x -lpthread

debug:
	g++ -ggdb ServerMain.cpp ServerFunct.cpp ServerFunct.h  -o BattleShipServer.dbg -std=c++0x -lpthread
